board_manager:
    additional_urls:
    - https://arduino.esp8266.com/stable/package_esp8266com_index.json
daemon:
  port: "50051"
directories:
  data: /Users/spiderock/Library/Arduino15
  downloads: /Users/spiderock/Library/Arduino15/staging
  user: /Users/spiderock/Documents/Arduino
logging:
  file: ""
  format: text
  level: info
